CREATE TABLE brand (
    BrandId  INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    BrandName VARCHAR(140) NOT NULL ,
    BrandLogo VARCHAR(130) NOT NULL,
    CreatdOn DATETIME NOT NULL,
    Website VARCHAR (100),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE brand MODIFY COLUMN UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
