CREATE TABLE Category(
    CategoryId INT AUTO_INCREMENT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    CategoryName VARCHAR(100) NOT NULL UNIQUE,
    CreateAt DATE,
    UpdateAt DATE
);

ALTER TABLE Category MODIFY COLUMN UpdateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
