CREATE TABLE `product` (
  `ProductId` int NOT NULL AUTO_INCREMENT,
  `ProductTitle` varchar(255) NOT NULL,
  `ProductImg` varchar(100) DEFAULT NULL,
  `ProductDesc` varchar(1000) DEFAULT NULL,
  `ProductSpecification` varchar(1000) DEFAULT NULL,
  `ProductPrice` float NOT NULL,
  `CateGoryId` int NOT NULL,
  `QuantityOnHand` int NOT NULL DEFAULT '0',
  `ProductKeywords` varchar(200) DEFAULT NULL,
  `ProductStatus` varchar(20) DEFAULT 'Available',
  `CreateAt` datetime NOT NULL,
  `UpdateAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `BrandId` int DEFAULT NULL,
  PRIMARY KEY (`ProductId`),
  KEY `CategoryId` (`CateGoryId`),
  KEY `fk_BrandId` (`BrandId`),
  CONSTRAINT `CategoryId` FOREIGN KEY (`CateGoryId`) REFERENCES `category` (`CategoryId`),
  CONSTRAINT `fk_BrandId` FOREIGN KEY (`BrandId`) REFERENCES `brand` (`BrandId`),
  CONSTRAINT `product_chk_1` CHECK ((`ProductPrice` > 0)),
  CONSTRAINT `product_chk_2` CHECK ((`QuantityOnHand` >= 0))
) ENGINE=InnoDB AUTO_INCREMENT=198 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci