-- Active: 1675590543659@@127.0.0.1@3306@c_m_surgimed
CREATE TABLE Users(
    UserId INT AUTO_INCREMENT NOT NULL PRIMARY KEY UNIQUE,
    UserName VARCHAR(30) NOT NULL,
    FirstName VARCHAR(40) NOT NULL ,
    LastName VARCHAR(40) NOT NULL,
    MobileNumber VARCHAR(15) NOT NULL UNIQUE,
    Email VARCHAR(320) NOT NULL UNIQUE,
    AccountPassword CHAR(64) NOT NULL,
    UserAddress VARCHAR(255) NOT NULL,
    ProfilePicture VARCHAR(100) NOT NULL
);

ALTER TABLE Users ADD COLUMN Catptcha BOOLEAN DEFAULT False;

ALTER TABLE Users RENAME COLUMN Catptcha TO Captcha;
ALTER TABLE Users ADD COLUMN Dob DATE NOT NULL;
ALTER TABLE Users MODIFY ProfilePicture VARCHAR(100) NULL;
ALTER TABLE Users ADD COLUMN Gender VARCHAR(6) NOT NULL;
ALTER TABLE Users MODIFY COLUMN MobileNumber VARCHAR(15) NULL;
ALTER TABLE Users MODIFY COLUMN UserAddress VARCHAR(255) NULL;